import mongoose from "mongoose";
const schema = mongoose.Schema;

let student = new schema({
    Sl_No:{
        type:Number
    },
    clg:{
        type:String
    },
    Roll_No:{
        type:String
    },
    Student_Name:{
        type:String
    },
    Branch:{
        type:String
    },
    Semester:{
        type:String
    },
    Section:{
        type:String
    },
    Admission_No:{
        type:String
    },
    Date_of_Admission:{
        type:String
    },
    Gender:{
        type:String
    },
    Category:{
        type:String
    },
    Nationality:{
        type:String
    },
    Religion:{
        type:String
    },
    Date_Of_Birth:{
        type:String
    },
    Mobile_No:{
        type:String
    },
    Whatsapp_No:{
        type:String
    },
    E_mail:{
        type:String
    },
    Entrance_Type:{
        type:String
    },
    Rank:{
        type:Number
    },
    Appeared_JEE:{
        type:String
    },
    JEE_Rank:{
        type:String
    },
    Seat_Type:{
        type:String
    },
    Scholarship:{
        type:String
    },
    EWS:{
        type:String
    },
    ID_Marks:{
        type:String
    },
    Mother_Toungue:{
        type:String
    },
    Aadharcard_No:{
        type:String
    },
    Ration_Card_No:{
        type:String
    },
    Bank_AC_No:{
        type:String
    },
    Blood_Group:{
        type:String
    },
    Last_Studied_Institute:{
        type:String
    },
    SSC_Board:{
        type:String
    },
    SSC_HT_No:{
        type:String
    },
    SSC_Institute:{
        type:String
    },
    SSC_Institute_Location:{
        type:String
    },
    SS_Yearof_pass:{
        type:String
    },
    SSC_Max_Marks:{
        type:String
    },
    SSC_Obtained:{
        type:String
    },
    SSC_Persentage:{
        type:String
    },
    SSC_GradePoints:{
        type:String
    },
    SSC_Long_Memo:{
        type:String
    },
    SSC_Short_Memo:{
        type:String
    },
    SSC_Other_Certificates:{
        type:String
    },
    Inter_Board:{
        type:String
    },
    Inter_HT_No:{
        type:String
    },
    Inter_Institute:{
        type:String
    },
    Inter_Institute_Location:{
        type:String
    },
    Inter_Yearof_pass:{
        type:String
    },
    Inter_Max_Marks:{
        type:String
    },
    Inter_Obtained:{
        type:String
    },
    Inter_Persentage:{
        type:String
    },
    Inter_GradePoints:{
        type:String
    },
    Inter_Group_Max_marks:{
        type:String
    },
    Inter_Group_Obtained_marks:{
        type:String
    },
    Inter_Group_Persentage:{
        type:String
    },
    Inter_Long_Memo:{
        type:String
    },
    Inter_Short_Memo:{
        type:String
    },
    Inter_TC:{
        type:String
    },
    Inter_Migration:{
        type:String
    },
    Inter_Other_Certificates:{
        type:String
    },
    Diploma_Board:{
        type:String
    },
    Diploma_HT_No:{
        type:String
    },
    Diploma_Institute:{
        type:String
    },
    Diploma_Institute_Location:{
        type:String
    },
    Diploma_Yearof_pass:{
        type:String
    },
    Diploma_Max_Marks:{
        type:String
    },
    Diploma_Obtained:{
        type:String
    },
    Diploma_PC:{
        type:String
    },
    Diploma_TC:{
        type:String
    },
    Diploma_Migration:{
        type:String
    },
    Diploma_Pased_Memos:{
        type:String
    },
    Degree_Board:{
        type:String
    },
    Degree_HT_No:{
        type:String
    },
    Degree_Institute:{
        type:String
    },
    Degree_Institute_Location:{
        type:String
    },
    Degree_Yearof_pass:{
        type:String
    },
    Degree_Max_Marks:{
        type:String
    },
    Degree_Obtained:{
        type:String
    },
    Degree_PC:{
        type:String
    },
    Degree_CMM:{
        type:String
    },
    Degree_TC:{
        type:String
    },
    Degree_Other_Certificates:{
        type:String
    },
    Father_Name:{
        type:String
    },
    Father_Occupation_Type:{
        type:String
    },
    Father_Occupation:{
        type:String
    },
    Father_Department:{
        type:String
    },
    Income:{
        type:Number
    },
    Father_Mobile_No:{
        type:String
    },
    Father_Whatsapp_No:{
        type:String
    },
    Land_Line:{
        type:String
    },
    Father_E_mail:{
        type:String
    },
    Mother_Name:{
        type:String
    },
    Mother_Occupation:{
        type:String
    },
    Mother_Mobile:{
        type:String
    },
    Mother_Whatsapp_No:{
        type:String
    },
    Mother_E_mail:{
        type:String
    },
    Door_No:{
        type:String
    },
    Street:{
        type:String
    },
    Village:{
        type:String
    },
    Mandal:{
        type:String
    },
    District:{
        type:String
    },
    State:{
        type:String
    },
    Country:{
        type:String
    },
    PIN_Code:{
        type:String
    },
    Land_Mark:{
        type:String
    },
    Permanent_Address:{
        type:String
    },
    Correspondence_Address:{
        type:String
    }
})

export default mongoose.model('Students_Data',student)